// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import java.util.concurrent.TimeUnit;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Constants;
import frc.robot.subsystems.Grabber;
import frc.robot.subsystems.Winch;
import frc.robot.subsystems.PIDDriveTrain;
import java.util.concurrent.TimeUnit;



 
public class AutonomousCommand2 extends CommandBase {

    private Grabber m_Grabber;
    private Winch m_Winch;
    private PIDDriveTrain m_DriveTrain;
    private int sleepCounter;


    public AutonomousCommand2(Grabber Grabber_sub, Winch Winch_sub, PIDDriveTrain DriveTrain_sub) {
        m_Grabber = Grabber_sub;
        m_Winch = Winch_sub;
        m_DriveTrain = DriveTrain_sub;
        sleepCounter = 0;
        m_DriveTrain.setBrakeMode();

    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Wait for a certain amount of time, easier to use this rather than repeating the try/catch
    private void wait(int timeInMS){
        try {
            Thread.sleep(timeInMS);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        sleepCounter = sleepCounter + 1;
        if(sleepCounter == 1){
            System.out.println("STARTING PHASE 1");
            m_Winch.moveservo();
        }
        else if(sleepCounter == 30){
            System.out.println("STARTING PHASE 2");
            m_Grabber.open();
        }
        else if(sleepCounter == 31){
            m_Grabber.stop();
            System.out.println("STARTING PHASE 3");
            while(Constants.RevPerFoot*(-17) < m_DriveTrain.rightBackEncoder.getPosition()) {
                m_DriveTrain.drive(-0.65,0.65);
            }
            m_DriveTrain.drive(0, 0);
            System.out.println("STARTING PHASE 3 END");
        }
        
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {  
        if (sleepCounter > Constants.sleepCounterConstant)
        {
            m_DriveTrain.drive(0, 0);
            sleepCounter = 0;
            m_DriveTrain.setCoastMode();
            return true;
        }
        else 
            return false;


    }

    @Override
    public boolean runsWhenDisabled() {

        return false;


    }
}
